### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by wuxian0** [YuxinSun/Stability-Selection#1]
请问您这是在复现其他的文章esclusive group lasso的过程么，还是您自己发的文章。我在使用exclusive group lasso时，W是一个矩阵，迭代过程中，发现这一项特别大，影响了整个目标函数的计算，不知道您遇到过么。我取正则项系数大于1e-4时就会导致计算错误

**Comment by yuxinsun** [comment]
您好，这个repo是优化excl. group lasso的算法的

原文: https://proceedings.neurips.cc/paper/2014/hash/43feaeeecd7b2fe2ae2e26d917b6477d-Abstract.html
这个repo我的文章：https://arxiv.org/abs/2002.12460

我印象中 $\lambda$ 确实不能太大，cross validation我一般用 $2^{-15}, \cdots 2^{15}$ 这个区间，最优解大部分时候都在这个区间中间或者偏左。不过没有遇到 $\lambda > 10^{-4}$ 就出现计算错误的情况

**Comment by wuxian0** [comment]
感谢
